### ISSUE TITLE
Can't add question

### ISSUE THREAD

**Issue by ebugnet** [jhoopes/moodle-mod_activequiz#11] opened 2015-06-03 12:09 UTC
Moodle 2.9 / theme More

In a active quizz, when I press + button in front of a question, page is reloaded and a blank frame apear under Edit quiz.

Don't know why...

And no quesiion is added.

Éric
![1](https://cloud.githubusercontent.com/assets/1265014/7959522/25c31ad0-09fa-11e5-8991-2bf27f47a944.PNG)

![2](https://cloud.githubusercontent.com/assets/1265014/7959527/2b3b2476-09fa-11e5-9ea4-f9d5d6887279.PNG)

**Comment by jhoopes** [comment] 2015-06-04 21:35
Hi Eric,

This issue is for the same reason as your submit button issue.  Hopefully this is now fixed!

Thanks,

**Closed by jhoopes** 2015-06-04 21:35 UTC

**Comment by ebugnet** [comment] 2015-06-05 06:14
Thanks !

2015-06-04 23:35 GMT+02:00 jhoopes <notifications@github.com>:

> Hi Eric,
>
> This issue is for the same reason as your submit button issue. Hopefully
> this is now fixed!
>
> Thanks,
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jhoopes/moodle-mod_activequiz/issues/11#issuecomment-109061061>
> .
>



-- 

[image: http://eric.bugnet.fr] <http://eric.bugnet.fr>
eric.bugnet.fr

**Comment by lvmoine** [comment] 2017-03-09 14:25
My config:
Moodle 3.0.2 – theme More  (same problem with clean or Essential) - plugin Active Quiz 3.7 (2016030601)

I do not understand, the problem is supposedly settled but
I have the same problem as described previously.
Thank you for your help.
Laurence


![pb_active_quiz](https://cloud.githubusercontent.com/assets/26304064/23754211/78fa2c0a-04dc-11e7-88a7-53aa43071224.png)
